# Generated by Django 5.2.6 on 2025-09-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('merchandise', 'Merchandise')], default='apparel', max_length=20),
        ),
    ]
