# Generated by Django 5.2.6 on 2025-09-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_rating_product_stock_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
