# Generated by Django 5.2.6 on 2025-09-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
